spring:
  datasource:
    url: jdbc:mysql://112.74.32.237:3306/test?characterEncoding=utf8&serverTimezone=GMT
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: i98l10u02
    hikari:
      max-lifetime: 31000
jpa:
  database: MySQL
  show-sql: true
  hibernate:
    naming_strategy : org.hibernate.cfg.ImprovedNamingStrategy
